### ISSUE TITLE
Уточнение постановки задачи

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2017-6-graph2d#1]
Необходимо сформулировать общее представление о проекте — как будет выглядеть приложение для построения 2D-графиков и какими функциями оно будет обладать. Полученное представление следует описать в README.md в виде одного или нескольких абзацев. После этого данную задачу можно закрывать.

**Comment by Praepostor-IU9** [comment]
Общее представление сформулировано.
